language: java
os: linux
dist: bionic
jdk:
  - openjdk8
  - openjdk11
  - openjdk15
before_install: chmod +x gradlew
install: ./gradlew check --no-daemon --console=plain
script: ./gradlew build --no-daemon --console=plain
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/minecraft/deobfedDeps/providedDummy.jar
  - rm -f  $HOME/.gradle/caches/minecraft/deobfedDeps/compileDummy.jar
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email: false
